services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ./debug.env
    environment:
      PGDATA: /var/lib/postgresql/18/docker # in container 
    volumes:
      - pgdata:/var/lib/postgresql/18/docker   # <— mount at the parent that definitely exists to get it to host
    networks:
      - ordersys-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  ordersystem:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - ./debug.env
    ports:
      - "3000:3000"
    command: ["/ordersystem"]
    networks:
      - ordersys-net

networks:
  ordersys-net:

volumes:
  pgdata:
